[package]
name = "snake"
version = "0.1.0"
authors = ["Matt Mullins <mmullins@mmlx.us>"]

[dependencies]
rand = "0.3"
x11_client = { path = "../x11_client" }
byteorder = "1.0"
futures = "0.1.7"
tokio-core = "0.1.3"
tokio-uds = "0.1.1"
