[package]
name = "snake"
version = "0.1.0"
authors = ["Matt Mullins <mmullins@mmlx.us>"]

[dependencies]
termios = "0.2.2"
rand = "0.3"
time = "0.1.35"
timer = "0.1.6"
x11_client = { path = "../x11_client" }
