[package]
name = "snake"
version = "0.1.0"
authors = ["Matt Mullins <mmullins@mmlx.us>"]
edition = "2018"

[dependencies]
rand = "0.3"
x11_client = { git = "https://github.com/mokomull/x11_client.git" }
byteorder = "1.0"
futures = "0.1.7"
tokio = { version = "0.1.15" }
